import { DesktopIconData } from '../components/desktop-icon/desktop-icon.component';

export const APP_ICONS: DesktopIconData[] = [
  {
    id: 'my-info',
    name: 'About Me',
    icon: 'assets/images/icons/profile.png',
    type: 'application',
    position: { x: 20, y: 20 },
  },
  {
    id: 'explorer',
    name: 'Explorer',
    icon: 'assets/images/icons/explorer.png',
    type: 'application',
    position: { x: 20, y: 120 },
  },
  {
    id: 'calculator',
    name: 'Calculator',
    icon: 'pi pi-calculator',
    type: 'application',
    position: { x: 20, y: 220 },
  },
  {
    id: 'paint',
    name: 'Paint',
    icon: 'pi pi-palette',
    type: 'application',
    position: { x: 20, y: 320 },
  },
  {
    id: 'chinese-chess',
    name: 'Cờ Tướng',
    icon: 'assets/images/icons/chess.png',
    type: 'application',
    position: { x: 120, y: 20 },
  },
  {
    id: 'love',
    name: 'Love',
    icon: 'assets/images/icons/love.png',
    type: 'application',
    position: { x: 120, y: 220 },
  },
  {
    id: 'music',
    name: 'Music Player',
    icon: 'pi pi-youtube',
    type: 'application',
    position: { x: 120, y: 320 },
  },
  {
    id: 'expense',
    name: 'Quản lý Chi tiêu',
    icon: 'pi pi-wallet',
    type: 'application',
    position: { x: 220, y: 20 },
  },
  {
    id: 'business',
    name: 'Quản lý Bán hàng',
    icon: 'pi pi-shopping-cart',
    type: 'application',
    position: { x: 220, y: 120 },
  },
  {
    id: 'fb-id-finder',
    name: 'Facebook Scanner',
    icon: 'pi pi-facebook',
    type: 'application',
    position: { x: 220, y: 220 },
  },
  {
    id: 'graph-visualizer',
    name: 'Đồ thị & Thuật toán',
    icon: 'pi pi-sitemap',
    type: 'application',
    position: { x: 220, y: 320 },
  },
  {
    id: 'sieu-co',
    name: 'Siêu Cờ',
    icon: 'pi pi-th-large',
    type: 'application',
    position: { x: 320, y: 20 },
  },
  {
    id: 'image-search',
    name: 'Tìm Kiếm Ảnh',
    icon: 'pi pi-images',
    type: 'application',
    position: { x: 320, y: 120 },
  },
];

export const APP_SEARCH_CONFIG = {
  apps: APP_ICONS.map((icon) => ({
    id: icon.id,
    name: icon.name,
    type: 'application',
    category: 'Applications',
    description: getAppDescription(icon.id),
    keywords: getAppKeywords(icon.id),
  })),
};

function getAppDescription(appId: string): string {
  const descriptions: { [key: string]: string } = {
    calculator: 'Perform mathematical calculations and computations',
    'my-info': 'View personal information and portfolio details',
    love: 'Explore love and relationship content',
    explorer: 'Browse and manage files and folders',
    paint: 'Create drawings and artwork with various tools',
    music: 'Listen to music videos from YouTube with a curated playlist',
    expense:
      'Manage family expenses with Google Sheets integration, view spending history, and add new expenses',
    business:
      'Manage sales, materials, and costs with Google Sheets integration across multiple tabs (Menu, Materials, Costs)',
    'chinese-chess': 'Chơi cờ tướng và cờ úp với AI, phá thế cờ, nhiều giao diện đẹp mắt',
    'fb-id-finder': 'Tìm Facebook ID từ số điện thoại, tra cứu thông tin Facebook',
    'graph-visualizer':
      'Tạo và phân tích đồ thị, tìm đường đi ngắn nhất với các thuật toán Dijkstra, Bellman-Ford, Floyd-Warshall, A*',
    'sieu-co':
      'Siêu Cờ - Chơi Cờ Tướng, Cờ Úp, giải Cờ Thế với AI thông minh. Ghi chép kỳ phổ, nhiều theme đẹp mắt',
    'image-search':
      'Tìm kiếm hình ảnh tương tự sử dụng thuật toán Computer Vision: pHash, dHash, Color Histogram, Edge Detection',
  };
  return descriptions[appId] || 'Application';
}

function getAppKeywords(appId: string): string[] {
  const keywords: { [key: string]: string[] } = {
    calculator: ['math', 'calculate', 'compute', 'arithmetic', 'numbers'],
    'my-info': ['profile', 'personal', 'information', 'about', 'portfolio'],
    love: ['relationship', 'romance', 'heart', 'dating'],
    explorer: ['files', 'folders', 'browse', 'manage', 'directory'],
    paint: ['draw', 'art', 'design', 'canvas', 'creative'],
    music: [
      'youtube',
      'video',
      'songs',
      'audio',
      'player',
      'playlist',
      'stream',
      'listen',
      'pop',
      'rock',
      'jazz',
      'classical',
      'electronic',
      'artist',
      'album',
      'track',
    ],
    expense: [
      'expense',
      'chi tiêu',
      'quản lý',
      'tài chính',
      'spending',
      'budget',
      'money',
      'finance',
      'google sheets',
      'gia đình',
      'family',
      'tiền',
      'giao dịch',
      'transaction',
    ],
    business: [
      'business',
      'bán hàng',
      'quản lý',
      'sales',
      'materials',
      'costs',
      'menu',
      'nguyên liệu',
      'vật liệu',
      'chi phí',
      'google sheets',
      'inventory',
      'kho',
      'sản phẩm',
    ],
    'chinese-chess': [
      'cờ tướng',
      'co tuong',
      'xiangqi',
      'cờ úp',
      'co up',
      'ky vuong',
      'kỳ vương',
      'chess',
      'game',
      'board game',
      'trò chơi',
      'puzzle',
      'thế cờ',
      'the co',
      'chinese chess',
      'vietnam chess',
    ],
    'fb-id-finder': [
      'facebook',
      'fb',
      'id',
      'tìm facebook id',
      'tim facebook id',
      'số điện thoại',
      'so dien thoai',
      'phone',
      'find facebook id',
      'facebook id finder',
      'lookup',
      'search facebook',
    ],
    'graph-visualizer': [
      'graph',
      'đồ thị',
      'do thi',
      'graph visualization',
      'shortest path',
      'đường đi ngắn nhất',
      'duong di ngan nhat',
      'dijkstra',
      'bellman-ford',
      'floyd-warshall',
      'a-star',
      'algorithm',
      'thuật toán',
      'thuat toan',
      'node',
      'edge',
      'weighted graph',
      'directed graph',
      'undirected graph',
    ],
    'sieu-co': [
      'siêu cờ',
      'sieu co',
      'cờ tướng',
      'co tuong',
      'xiangqi',
      'cờ úp',
      'co up',
      'cờ thế',
      'co the',
      'puzzle chess',
      'chinese chess',
      'AI chess',
      'game',
      'kỳ phổ',
      'ky pho',
      'minimax',
      'alpha-beta',
    ],
    'image-search': [
      'image search',
      'tìm kiếm ảnh',
      'tim kiem anh',
      'hình ảnh tương tự',
      'hinh anh tuong tu',
      'similar image',
      'reverse image search',
      'phash',
      'dhash',
      'color histogram',
      'edge detection',
      'computer vision',
      'image matching',
      'so sánh ảnh',
      'so sanh anh',
      'thuật toán',
      'thuat toan',
      'perceptual hash',
    ],
  };
  return keywords[appId] || [];
}
